# config.yml

backend:
  name: github
  repo:  darkbeanbbq/test-netlifyCMS
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
